on:
  push:
    branches:
      - main
  
  pull_request:
      
name: Automated tests

jobs:
  automatedTests:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
     
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: Install git2r dependencies
        run: sudo apt-get install -y libgit2-dev

      - name: Install proj library (terra depdencies)
        run: sudo apt-get install libproj-dev
        
      - name: Install gdal library (terra dependencies)
        run: sudo apt-get install libgdal-dev
        
      - name: Install udunits library (units dependencies)
        run: sudo apt-get install libudunits2-dev

      - name: Cache renv packages
        id: cache-renv
        uses: actions/cache@v4
        with:
          path: cache-renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      
      - uses: r-lib/actions/setup-renv@v2
          
      - name: Run tests 
        shell: Rscript {0}
        run: |
          shinytest2::test_app()
          