on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '20 3 * * 0'

name: lintr

permissions:
  contents: read

jobs:
  lintr:
    runs-on: ${{ matrix.config.os }}

    name: Run lintr scanning

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, r: 'release'}

    permissions:
      contents: read # for checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      
      - name: restore renv
        uses: r-lib/actions/setup-renv@v2

      - name: Install lintr
        shell: Rscript {0}
        run: |
          renv::install("lintr")

      - name: Run lintr
        run: lintr::sarif_output(lintr::lint_dir("."), "lintr-results.sarif")
        shell: Rscript {0}
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: lintr-results.sarif
          wait-for-processing: true
